version: '3.10'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mongodb://mongo_db:27017
    depends_on:
      - mongo_db
    networks:
      - my_network

  mongo_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db
    networks:
      - my_network

volumes:
  mongo_volume:

networks:
  my_network: